<?php

session_start();
date_default_timezone_set('Asia/Manila');
include('util/connect.php');
include('util/class.misc.php');
include('util/mysqli.php'); 
include('util/classes.php'); 

if($_SESSION['Sort1']=='Asc'){
	$_SESSION['Sort1']='Desc';
}
else{
	$_SESSION['Sort1']='Asc';
}

?>
<?php
//for voucher hard code

if($_REQUEST['process']=='PettyCashVoucher'  || $_REQUEST['process']=='CashVoucher' 
|| $_REQUEST['process']=='ChequeVoucher' || $_REQUEST['process']=='FuelRequest' 
|| $_REQUEST['process']=='RequestLiquidationForm'){
	$keyname='PaymentMasterID';
	$tablename='paymentmaster';
	$heading='Process '.$_REQUEST['process'];
	$documentname='PaymentMasterName';
}

else{
	$keyname=$_REQUEST['process'].'ID';
	$tablename=strtolower($_REQUEST['process']);
	$heading=str_replace('Master','',$_REQUEST['process']);
	$documentname=$_REQUEST['process'].'Name';
}	


$mastertable=strtolower($heading).'master';
$detailtable=strtolower($heading).'detail';
$titlemaster='Process '.$heading.' Detail';
$autogenerated=0;				    
if($_REQUEST['process']=='Project'){
	$mastertable=strtolower($heading);
}




?>	
<div class="col-md-15 column">
<div class="table-responsive">
	
	<div STYLE=" height: 450px; width: 100%; font-size: 12px; overflow: auto;">
	<table  id="resulttable" name="resulttable" class="lighterbluetone" 
	 border="1" align="center" cellpadding="0" cellspacing="0" width="100%">
    
    <?php
 
	//base search query
	$groupquery=false;
	
	
	if($_REQUEST['process']=='Product'){
		
		$colspanfooter=7;
		$mastertable='product';
		$detailtable='paymentdetail';
		
		
			$insertsql="select t1.*,t1.PayTypeID,PayTypeName,t1.ProjectID,ProjectName,
			t1.Price-t1.Discount+t1.Interest-ifnull(sum(t4.Amount),0) as Balance
			from product t1 
			left join paytype t2 on t2.PayTypeID=t1.PayTypeID
			left join project t3 on t3.ProjectID=t1.ProjectID
			left join paymentdetail t4 on t4.ProductID=t1.ProductID 
			group by ProductID
			";
		print_r($insertsql);
				
	}
	
	
	elseif($_REQUEST['process']=='Project'){
		
		$insertsql="select t1.*
		from project t1
		group by t1.ProjectID ";
	}
	
	
	
	
    //check if FIRST searchkey is empty
    
    if ($_REQUEST['searchkey']!='' ){
		
		if ($_REQUEST['operator1']=="like" ){
			$insertsql.=" HAVING ". $_REQUEST['searchby']." like '%".trim($_REQUEST['searchkey'])."%' ";
		}
		elseif ($_REQUEST['operator1']=="is" ){
			$insertsql.=" HAVING ". $_REQUEST['searchby']." is  ".trim($_REQUEST['searchkey'])." ";
		}
		else{
			if($groupquery==true){
				$insertsql.=" HAVING ".$_REQUEST['searchby']." ".
				$_REQUEST['operator1']." '".trim($_REQUEST['searchkey'])."' ";
			}
			else{
				//if($_REQUEST['process']=='PettyCash'){
						//$insertsql.=" AND ".$_REQUEST['searchby3']." ".
						//$_REQUEST['operator3']." '".$_REQUEST['searchkey3']."' ";}
					
					//else{
				$insertsql.=" HAVING ".$_REQUEST['searchby']." ".
					$_REQUEST['operator1']." '".trim($_REQUEST['searchkey'])."' ";// }
			}
		}
	}
	
    	
    //check if second search key is not empty
    if ($_REQUEST['searchkey2']!='' ){
		
		//not empty first key append query using second operator
		if ($_REQUEST['searchkey']!='' ){
			if ($_REQUEST['operator2']=="like" ){
				$insertsql.=$_REQUEST['operand']." ". $_REQUEST['searchby2'].
				" like '%".$_REQUEST['searchkey2']."%' ";
			}
			else{
				$insertsql.=$_REQUEST['operand'] ." ".
				$_REQUEST['searchby2']." ".$_REQUEST['operator2']." '".trim($_REQUEST['searchkey2'])."'";
			}
			
		}
		else{
			//empty first key, check if operator is like and groupquery
			if ($_REQUEST['operator2']=="like" ){
				$insertsql.=" HAVING ". $_REQUEST['searchby2']." like '%".trim($_REQUEST['searchkey2'])."%' ";
			}
			else{
				if($groupquery==true){
					$insertsql.=" HAVING ".$_REQUEST['searchby2']." ".
					$_REQUEST['operator2']." '".trim($_REQUEST['searchkey2'])."' ";
				}
				else{
					//if($_REQUEST['process']=='PettyCash'){
						//$insertsql.=" AND ".$_REQUEST['searchby3']." ".
						//$_REQUEST['operator3']." '".$_REQUEST['searchkey3']."' ";}
					
					//else{
					$insertsql.=" HAVING ".$_REQUEST['searchby2']." ".
					$_REQUEST['operator2']." '".trim($_REQUEST['searchkey2'])."' ";//}
				}
			}
			
		}
		
	}
    
    if ($_REQUEST['searchkey3']!='' ){
		
		//not empty second key append query using second operator
		if ($_REQUEST['searchkey2']!='' ){
			if ($_REQUEST['operator3']=="like" ){
				$insertsql.=$_REQUEST['operand2']." ". $_REQUEST['searchby3'].
				" like '%".$_REQUEST['searchkey3']."%' ";
			}
			else{
				$insertsql.=$_REQUEST['operand2'] ." ".
				$_REQUEST['searchby3']." ".$_REQUEST['operator3']." '".trim($_REQUEST['searchkey3'])."'";
			}
			
		}
		else{
			//empty first key, check if operator is like and groupquery
			if ($_REQUEST['operator3']=="like" ){
				$insertsql.=" HAVING ". $_REQUEST['searchby3']." like '%".trim($_REQUEST['searchkey3'])."%' ";
			}
			else{
				if($groupquery==true){
					$insertsql.=" HAVING ".$_REQUEST['searchby3']." ".
					$_REQUEST['operator3']." '".trim($_REQUEST['searchkey3'])."' ";
				}
				else{
					//if($_REQUEST['process']=='PettyCash'){
						//$insertsql.=" AND ".$_REQUEST['searchby3']." ".
						//$_REQUEST['operator3']." '".$_REQUEST['searchkey3']."' ";}
					
					//else{
						$insertsql.=" HAVING ".$_REQUEST['searchby3']." ".
						$_REQUEST['operator3']." '".trim($_REQUEST['searchkey3'])."' ";//}
				}
			}
			
			
		}
		
	}
    
    	
    
	($_REQUEST['searchlimit'] == '0' || $_REQUEST['searchlimit'] == '')?
		$insertsql .= " order by ".$_REQUEST['orderby1']." ".$_REQUEST['sortby1']: 
		$insertsql .= " order by ".$_REQUEST['orderby1']." ".$_REQUEST['sortby1']. 
		" limit ".$_REQUEST['searchlimit']; 
	
	     
	if( $_REQUEST['process']=='Product'
	|| $_REQUEST['process']=='Project'
	
	){
		$sqlqry=$insertsql;
	}
	
	else{
		//print_r($insertsql);
		
		
		if (mysqli_query($conn, $insertsql) === TRUE) {
	    	//printf("Insert ok\n");
		}
		else{
			printf("Insert error!!! ".$insertsql.' '.mysqli_error($conn));
		}
		$sqlqry="select * from invoicequery use index(".$_REQUEST['searchby'].")";		
	}
	//$_SESSION['SqlQuery']=$sqlqry;
	//print_r($_REQUEST['operator1']);		
 	//print_r($sqlqry);
 	?>

 	<thead >
 	<?php	
	/* Select queries return a resultset */
	if ($result = mysqli_query($conn, $sqlqry)) {
		//printf("Select returned %d rows.\n", mysqli_num_rows($result));
		    
		$j=0;
				
		
		 
		
		if($_REQUEST['process']=='Product') { 
			$detailcolspan=12;
			$suminterest=0;
			?>
	    	
	    	<tr>
			<th class="lighterbluetone"  width="5%">ACTION 
				<input id="addmaster" type="image" src="../images/add.png" 
				title="Add <?php echo $heading ?>" width="20px" height="20" align="center"
				onclick=""/>
				<?php	include('GetCrudIcons.php'); ?>
			</th>
	    	<th class="lighterbluetone" width="10%"
	        	onClick="$('#orderby1').val('ProductName');
				$('#sortby1').val('<?php echo $_SESSION['Sort1'] ?>');
				document.getElementById('searchinvoicebtn').click()">
				Lot Name
	        </th>
	        <th class="lighterbluetone" width="8%"
	        	onClick="$('#orderby1').val('ProjectName');
				$('#sortby1').val('<?php echo $_SESSION['Sort1'] ?>');
				document.getElementById('searchinvoicebtn').click()">Project Name
			</th>
	        <th class="lighterbluetone" width="11%"
	        	onClick="$('#orderby1').val('ClientName');
				$('#sortby1').val('<?php echo $_SESSION['Sort1'] ?>');
				document.getElementById('searchinvoicebtn').click()">Client Name
			</th>
			<th class="lighterbluetone" width="10%"
	        	onClick="$('#orderby1').val('ClientAddress');
				$('#sortby1').val('<?php echo $_SESSION['Sort1'] ?>');
				document.getElementById('searchinvoicebtn').click()">Client Address
			</th>
			<th class="lighterbluetone" width="5%"
	        	onClick="$('#orderby1').val('ClientPhoneNo');
				$('#sortby1').val('<?php echo $_SESSION['Sort1'] ?>');
				document.getElementById('searchinvoicebtn').click()">Client Phone
			</th>
			<th class="lighterbluetone" width="6%"
	        	onClick="$('#orderby1').val('BeneficiaryName');
				$('#sortby1').val('<?php echo $_SESSION['Sort1'] ?>');
				document.getElementById('searchinvoicebtn').click()">Beneficiary Name
			</th>
			<th class="lighterbluetone" width="5%"><strong>Price</strong></th>
			<th class="lighterbluetone" width="5%"><strong>Discount</strong></th>
			<th class="lighterbluetone" width="5%"><strong>Interest</strong></th>
			<th class="lighterbluetone" width="3%"><strong>MO/s</strong></th>
			<th class="lighterbluetone" width="5%"
	        	onClick="$('#orderby1').val('SoldDate');
				$('#sortby1').val('<?php echo $_SESSION['Sort1'] ?>');
				document.getElementById('searchinvoicebtn').click()">Date Sold
			</th>
			<th class="lighterbluetone" width="5%"
	        	onClick="$('#orderby1').val('PayTypeName');
				$('#sortby1').val('<?php echo $_SESSION['Sort1'] ?>');
				document.getElementById('searchinvoicebtn').click()">Pay Type
			</th>
			<th class="lighterbluetone" width="5%"
	        	onClick="$('#orderby1').val('Balance');
				$('#sortby1').val('<?php echo $_SESSION['Sort1'] ?>');
				document.getElementById('searchinvoicebtn').click()">Balance
			</th>
			<th class="lighterbluetone" width="12%"><strong>Remarks</strong></th>
			</tr>
	    	<?php 
	    }
	   
		
		elseif($_REQUEST['process']=='Project'){ 
        	$colspan=8;
        	$colspanfooter=10;
        	$titlemaster='Project';
        	$detailcolspan=9;
        	$detailtable='paymentmaster';
        	$sumestimatedcost=0;
        	$sumactualcost=0;
        	?>
        	<tr class="">
			<th class="lighterbluetone" width="10%">ACTION
				<input id="addmaster" type="image" src="../images/add.png" 
				title="Add <?php echo $heading ?>" width="20px" height="20" align="center"
				onclick=""/>
				<?php	include('GetCrudIcons.php'); ?>
			</th>
			<th class="lighterbluetone" width="30%"
        		onClick="$('#orderby1').val('ProjectName');
				$('#sortby1').val('<?php echo $_SESSION['Sort1'] ?>');
				document.getElementById('searchinvoicebtn').click()">
        		<u>PROJECT NAME</u>
        	</th>
        	
        	<th class="lighterbluetone" width="30%"
        		onClick="$('#orderby1').val('Location');
				$('#sortby1').val('<?php echo $_SESSION['Sort1'] ?>');
				document.getElementById('searchinvoicebtn').click()">
        		<u>LOCATION</u>
        	</th>
        	
        	<th class="lighterbluetone" width="10%"><strong>COMPLETED DATE</strong></th>
	        <th class="lighterbluetone" width="20%"><strong>REMARKS</strong></th>
	        <?php 
	    }
	   
		//Weekly PayRoll
		 ?>
		
    	</thead>
		<?php
		
		$allresult=array();
		$sumqty=0;
		$sumprice=0;
		$sumdiscount=0;
		$sumamount=0;
		$sumamountcancel=0;
		$sumbalance=0; 
		$paid=0; $unpaid=0;
		$ctr=0;
		$sumunpoured=0;
		$sumexcess=0;
		//$allresult=mysqli_fetch_array($result);
		while($rowdetail = mysqli_fetch_array($result)){
  						
			if($_REQUEST['process']=='ServiceOrderMaster'){
				$autogenerated=$rowdetail['AutoGenerated'];
			}	
			// toggle shading rows //modified joeben no alt per row plane color just hover
			array_push($allresult,$rowdetail);	
			
			
			++$ctr;			
			if($j++ % 2 == 0){
				$shaded = "shaded";
				$bgcolor ='#ebeaec';
			}
			else{
				$shaded = "noshade";
				$bgcolor = '#fcfeed';
			}		
			?>
            <tr class="hovjob <?php echo $shaded ?>"  	id="trdetail_<?php echo $rowdetail[$keyname] ?>" >
            	<?php
    			if($_REQUEST['process']=='SalesProductionOutput'){
    				?>
    				
    				<?php
				}
				else{
					
				
				?>
				
            	<td class="griditems minwidth" width="8%">
            		<?php echo $ctr; ?>
            		
            		<!-- Open Detail -->
            		
	    			<input id="opendetail_<?php echo $rowdetail[$keyname] ?>" 
	    			type="image" src="../images/folderclose.ico"
	    			width="20px" height="20px" align="center" 
	    			title="<?php echo $titlemaster; ?>"
	    			onclick="changeImage('opendetail_<?php echo $rowdetail[$keyname] ?>');
	    			ShowTransactionDetail0('<?php echo $keyname ?>',
		            '<?php echo $rowdetail[$keyname]?>',
		            '<?php echo ($_REQUEST['process']=='ForProduction')?'ServiceOrderMaster':$_REQUEST['process'] ?>',
		            'detailaccord_<?php echo $rowdetail[$keyname] ?>',0,'',
		            '<?php echo $rowdetail[$documentname] ?>');"
	    			/>
	    			
	    			
            		
	    			<!-- additional button for Cheque PaymentVoucher -->
	    			<?php
	    			if($_REQUEST['process']=='ChequeVoucher' || $_REQUEST['process']=='CollectionMaster'){
	    				$documentname='PaymentMasterName';
						?>
						<input id="opendetail2_<?php echo $rowdetail[$keyname] ?>" 
		    			type="image" src="../images/folderclose2.png"
		    			width="20px" height="20px" align="center" 
		    			title="Process Cheque Payments"
		    			onclick="changeImage2('opendetail2_<?php echo $rowdetail[$keyname] ?>');
		    			ShowTransactionDetail0('<?php echo $keyname ?>',
			            '<?php echo $rowdetail[$keyname]?>',
			            'PaymentChequeMaster',
			            'detailaccord_<?php echo $rowdetail[$keyname] ?>',0,'',
			            '<?php echo $rowdetail['PaymentMasterName'] ?>');"
		    			/>
						<?php	
					}
					?>
										
	    			<!-- Printing by Form-->
	    			<?php
	    			if($_REQUEST['process']=='PettyCashVoucher' ){
	    				?>
	    				
		    			<input id="Print<?php echo $rowdetail[$_REQUEST['process'].'ID'] ?>" 
	            		name="Print<?php echo $rowdetail[$_REQUEST['process'].'ID'] ?>" 
						class="buttonedit" type="image" src="../images/print_pr.png" 
						 align="center" 
						alt="Print Voucher <?php echo $_REQUEST['process'] ?>"
						title="Print <?php echo $_REQUEST['process'] ?>"
						onClick="PrintVoucher(<?php echo $rowdetail[$keyname] ?>,
						'<?php echo $rowdetail['VoucherTypeName'] ?>'
						)"/>
						
						<?php
					}
					else {
						?>
						
						<input id="Print<?php echo $rowdetail[$keyname] ?>" 
		        		name="Print<?php echo $rowdetail[$keyname] ?>" 
						class="buttonedit" type="image" src="../images/print_pr.png" 
						 align="center" 
						alt="Print Form <?php echo $_REQUEST['process'] ?>"
						title="Print Form <?php echo $_REQUEST['process'] ?>"
						onClick="PrintForm(<?php echo $rowdetail[$keyname] ?>,
						'<?php echo strtolower($_REQUEST['process']) ?>_<?php echo 
				        $_REQUEST['process'] ?>Name_<?php echo $rowdetail[$keyname] ?>',
						'<?php echo $_REQUEST['process'] ?>')"/>
						
						<?php
					}
					?>
					
					<!-- additional button for Service Order using continuous form -->
	    			<?php
	    			if($_REQUEST['process']=='ServiceOrderMaster' 
	    			){
						?>
						<input id="Print<?php echo $rowdetail[$keyname] ?>" 
		        		name="Print<?php echo $rowdetail[$keyname] ?>" 
						class="buttonedit" type="image" src="../images/printnew.ico" 
						align="center" height="50px" width="50px"
						alt="Print Form <?php echo $_REQUEST['process'] ?> in continuous form"
						title="Print Form <?php echo $_REQUEST['process'] ?> in continuous form"
						onClick="PrintForm(<?php echo $rowdetail[$keyname] ?>,
						'<?php echo strtolower($_REQUEST['process']) ?>_<?php echo 
				        $_REQUEST['process'] ?>Name_<?php echo $rowdetail[$keyname] ?>',
						'<?php echo $_REQUEST['process'] ?>Continuous')"/>
						<?php	
					}
					?>
					
					
					<?php
					//restrict delete 
					//print_r($rowdetail['EncodedBy']);
					if((($rowdetail['EncodedBy']==$_SESSION['_Employee']['EmployeeID']) ||
					 $_SESSION['_Employee']['Username']=='admin') && ($autogenerated==0)) {
						if ($_REQUEST['process']<>'ForProduction'){
							
						
						?>
						
						
						<input id="DeleteInvoiceDet" class="buttondelete" 
						type="image" src="../images/delete.png" 
						 align="center" 
						title="Delete This Row# <?php echo $rowdetail[$keyname] ?>"  
						onClick="DeleteCascade('<?php echo strtolower($mastertable) ?>',
						'<?php echo strtolower($detailtable) ?>','',
						'<?php echo $keyname ?>',
						<?php echo $rowdetail[$keyname] ?>);
						document.getElementById('searchinvoicebtn').click();"
						/>	
						<?php
						}
					}
					?>
					
				
    			</td>
    			
            	<?php
            	}
            	if($_REQUEST['process']=='Product'){ ?>
	            	
	            	<td id="<?php echo $tablename ?>_<?php 
			   		echo $_REQUEST['process'].'Name' ?>_<?php echo $rowdetail[$keyname] ?>" class="griditems"
					<?php echo ($rowdetail['EncodedBy']==$_SESSION['_Employee']['EmployeeID'])? 'contenteditable="true"': ''?> >
					<?php echo $rowdetail[$_REQUEST['process'].'Name']; ?>
					</td>
					
				    <td class="griditems">
				    	<?php
					    $DataEntry= new DataEntry();
					    $Table=$DataEntry->DatalistEntry($tablename,'ProjectName',
					    $rowdetail[$keyname],$rowdetail['ProjectID'],
					    $rowdetail['ProjectName'],'Project','','','','','','','',150,
					    $bgcolor,$rowdetail['EncodedBy']);
					    ?>	
				    </td>
				    
				    <td id="<?php echo $tablename ?>_ClientName_<?php echo $rowdetail[$keyname] ?>"
						contenteditable="true" class="griditems" >
						<?php echo $rowdetail['ClientName']; ?>
					</td>
					
					<td id="<?php echo $tablename ?>_ClientAddress_<?php echo $rowdetail[$keyname] ?>"
						contenteditable="true" class="griditems" >
						<?php echo $rowdetail['ClientAddress']; ?>
					</td>
					
					<td id="<?php echo $tablename ?>_ClientPhone_<?php echo $rowdetail[$keyname] ?>"
						contenteditable="true" class="griditems" >
						<?php echo $rowdetail['ClientPhone']; ?>
					</td>
					
					<td id="<?php echo $tablename ?>_BeneficiaryName_<?php echo $rowdetail[$keyname] ?>"
						contenteditable="true" class="griditems" >
						<?php echo $rowdetail['BeneficiaryName']; ?>
					</td>
					
					<td id="<?php echo $tablename ?>_Price_<?php echo $rowdetail[$keyname] ?>"
						contenteditable="true" class="gridrightitems" >
						<?php echo $rowdetail['Price']; ?>
					</td>
					
					<td id="<?php echo $tablename ?>_Discount_<?php echo $rowdetail[$keyname] ?>"
						contenteditable="true" class="gridrightitems" >
						<?php echo $rowdetail['Discount']; ?>
					</td>
					
					<td id="<?php echo $tablename ?>_Interest_<?php echo $rowdetail[$keyname] ?>"
						contenteditable="true" class="gridrightitems" >
						<?php echo $rowdetail['Interest']; ?>
					</td>
					
					<td id="<?php echo $tablename ?>_MonthsToPay_<?php echo $rowdetail[$keyname] ?>"
						contenteditable="true" class="gridrightitems" >
						<?php echo $rowdetail['MonthsToPay']; ?>
					</td>
					
					<td class="griditems">
						<?php 
						$DataEntry= new DataEntry();
						$DataEntry->DateEntry($tablename,'SoldDate',
						$rowdetail[$keyname],$rowdetail['SoldDate'],
						$bgcolor,$rowdetail['EncodedBy']);	
						?>
					</td>
					
					<td class="griditems">
				    	<?php
					    $DataEntry= new DataEntry();
					    $Table=$DataEntry->DatalistEntry($tablename,'PayTypeName',
					    $rowdetail[$keyname],$rowdetail['PayTypeID'],
					    $rowdetail['PayTypeName'],'PayType','','','','','','','',60,
					    $bgcolor,$rowdetail['EncodedBy']);
					    ?>	
				    </td>
				    
				    <td id="<?php echo $tablename ?>_Balance_<?php echo $rowdetail[$keyname] ?>"
						contenteditable="true" class="gridrightitems" >
						<?php echo number_format($rowdetail['Balance'],2); ?>
					</td>
					
				   
				    				    
				    <td id="<?php echo $tablename ?>_Remarks_<?php echo $rowdetail[$keyname] ?>"
						 contenteditable="true" class="griditems" >
						<?php echo $rowdetail['Remarks']; ?>
					</td>
	        		
				<?php
					$sumamount+=$rowdetail['Price'];
					$sumdiscount+=$rowdetail['Discount'];
					$suminterest+=$rowdetail['Interest'];
					$sumbalance+=$rowdetail['Balance'];
					
					
				} 
				
				
				elseif($_REQUEST['process']=='Project') { 
                	$mastertable='project';
                	$detailtable='paymentmaster'
            		?>
				   	
				    
				    <td class="griditems" 
					    <?php echo ($rowdetail['EncodedBy']==$_SESSION['_Employee']['EmployeeID'])?
					     'contenteditable="true"': ''?>
		 				id="<?php echo $tablename ?>_ProjectName_<?php echo $rowdetail[$keyname]?>">
						<?php echo $rowdetail['ProjectName']; ?>
					</td>
				    
				    <td class="griditems"
					    <?php echo ($rowdetail['EncodedBy']==$_SESSION['_Employee']['EmployeeID'])?
					     'contenteditable="true"': ''?>
		 				id="<?php echo $tablename ?>_Location_<?php echo $rowdetail[$keyname]?>">
						<?php echo $rowdetail['Location']; ?>
					</td>
				    
				    <td class="griditems">
						<?php 
						$DataEntry= new DataEntry();
						$DataEntry->DateEntry($tablename,'CompletedDate',
						$rowdetail[$keyname],$rowdetail['CompletedDate'],
						$bgcolor,$rowdetail['EncodedBy']);	
						?>
					</td>
				    
				    <td class="griditems"
					    <?php echo ($rowdetail['EncodedBy']==$_SESSION['_Employee']['EmployeeID'])?
					     'contenteditable="true"': ''?>
		 				id="<?php echo $tablename ?>_Remarks_<?php echo $rowdetail[$keyname]?>">
						<?php echo $rowdetail['Remarks']; ?>
					</td>
				   <?php
	            	
	            } 
				
				
				
	         ?>  
             </tr>
            
            <tr><!-- dito nakalagay ang detail transaction-->
            	<td colspan="<?php echo $detailcolspan ?>"
            		<div id="detailaccord_<?php echo $rowdetail[$keyname] ?>"></div>
            	</td>
            	<!-- payment module -->
            	<?php
				if($_REQUEST['process']=='ServiceOrderMaster'){
					?>
	            	<td colspan="6">
	            		<div id="paymentdetailaccord_<?php echo $rowdetail[$keyname] ?>"></div>
	            	</td>
	            	<?php
            	}
            	?>
            </tr>
            
             <?php
             
			}
    	
 		$_SESSION['result']=$allresult;
		/* free result set */
	    mysqli_free_result($result);
    	
    	?>
    	 <tr class="hovjob">
    	 	<?php
			if($_REQUEST['process']=='Product' ){
				?>
				<td class="gridtotalrightitems" colspan="<?php echo $colspanfooter ?>">
				<strong>TOTAL</strong>
				</td>
				<td class="gridtotalrightitems" ><?php echo number_format($sumamount,2)?></td>
				<td class="gridtotalrightitems" ><?php echo number_format($sumdiscount,2)?></td>
	     		<td class="gridtotalrightitems"><?php echo number_format($suminterest,2)?></td>	
	     		<td class="gridtotalrightitems" colspan="4"><?php echo number_format($sumbalance,2)?></td>	
	     		<td class="gridtotalrightitems">&nbsp;</td>		
	     		<?php
			}
			
			elseif($_REQUEST['process']=='PettyCashVoucher'){
				?>
				<td class="gridtotalrightitems" colspan="4">
				<strong>TOTAL</strong>
				</td>
				<td class="gridtotalrightitems"><?php echo number_format($sumpaymentamount,2)?></td>
	     		<td class="gridtotalrightitems"><?php echo number_format($sumliquidatedamount,2)?></td>
	     		<td class="gridtotalrightitems"><?php echo number_format($sumunliquidatedamount,2)?></td>
	     		<td class="gridtotalrightitems" colspan="8">&nbsp;</td>		
	     		<?php
			}
			elseif($_REQUEST['process']=='ChequeVoucher'){
				?>
				<td class="gridtotalrightitems" colspan="3">
				<strong>TOTAL</strong>
				</td>
				<td class="gridtotalrightitems"><?php echo number_format($sumamount,2)?></td>
	     		<td class="gridtotalrightitems" colspan="2">&nbsp;</td>	
	     		<td class="gridtotalrightitems"><?php echo number_format($sumoramount,2)?></td>
	     		<td class="gridtotalrightitems" colspan="6">&nbsp;</td>		
	     		<?php
			}
			elseif($_REQUEST['process']=='CashVoucher'){
				?>
				<td class="gridtotalrightitems" colspan="3">
				<strong>TOTAL</strong>
				</td>
				<td class="gridtotalrightitems"><?php echo number_format($sumamount,2)?></td>
	     		<td class="gridtotalrightitems" colspan="2">&nbsp;</td>	
	     		<td class="gridtotalrightitems"><?php echo number_format($sumoramount,2)?></td>
	     		<td class="gridtotalrightitems" colspan="6">&nbsp;</td>		
	     		<?php
			}
			
			
					
	     	?>
    	 </tr>
    	<?php
    }
	else{
		die(mysqli_error($conn));
	}	    
    ?>
    </table>																					
    </div>  

</div> 
</div>
